services:
  migrate:
    build:
      context: .
      target: builder
    command: npx prisma migrate deploy
    env_file:
      - .env.production
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subvencao-2026
    restart: unless-stopped
    ports:
      - "3301:3301"
    env_file:
      - .env.production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      migrate:
        condition: service_completed_successfully
