import type { Metadata } from "next";
import "./globals.css";
import RouteHeader from "./components/RouteHeader";
import { DM_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Subvenção para requalificação de imóveis no centro",
  description: "Generated by create next app",
};

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={`${dmSans.className} antialiased`}>
        <RouteHeader />
        {children}
      </body>
    </html>
  );
}
