import type { Metadata } from "next";
import "./globals.css";
import RouteHeader from "./components/RouteHeader";

export const metadata: Metadata = {
  title: "Subvenção para requalificação de imóveis no centro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        <RouteHeader />
        {children}
      </body>
    </html>
  );
}
