export const chamamentos2025 = [
  {
    id: "group-1",
    headerTitle: "Chamamento Público n° 01/2025/SMUL",
    items: [
      {
        id: 1,
        title: "Basílio177",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Rua Basílio da Gama, n° 177 - República, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Retrofit 74 Empreendimento Imobiliário SPE Ltda.",
        cnpj: "CNPJ: 44.179.233/0001-79",
        tableUrl: "/documents/1-Tabela-de-Pontuacao-Retrofit74.pdf",
        planUrl: "/documents/1-Plano-Urbanistico-Retrofit74.pdf",
        cards: [
          { label: "Pontuação", value: "89,7815" },
          { label: "% Subvenção", value: "22,45%" },
          { label: "Valor da Subvenção", value: "R$ 2.307.357,78", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 2.068.622,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 2,
        title: "Edifício Copan",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Av. Ipiranga, n° 200 - Centro Histórico de São Paulo, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Condomínio Edifício Copan",
        cnpj: "CNPJ: 54.535.828/0001-73",
        tableUrl: "/documents/2-Tabela-de-Pontuacao-COPAN.pdf",
        planUrl: "/documents/2-Plano-Urbanistico-COPAN.pdf",
        cards: [
          { label: "Pontuação", value: "89,45" },
          { label: "% Subvenção", value: "22,36%" },
          { label: "Valor da Subvenção", value: "R$ 13.390.961,80", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 3,
        title: "JB104",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Rua José Bonifácio, n° 104 - Centro Histórico de São Paulo, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: IRR - Informação e Hospedagem Ltda.",
        cnpj: "CNPJ: 28.032.148/0001-27",
        tableUrl: "/documents/3-Tabela-de-Pontuacao-IRR-Jose-Bonifacio.pdf",
        planUrl: "/documents/3-Plano-Urbanistico-IRR-Jose-Bonifacio.pdf",
        cards: [
          { label: "Pontuação", value: "81" },
          { label: "% Subvenção", value: "25%" },
          { label: "Valor da Subvenção", value: "R$ 3.076.938,50", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 4,
        title: "Edifício Martinelli",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Av. São João, n° 35 - Centro Histórico de São Paulo, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Bar e Restaurante Tokyo SP 110 Ltda.",
        cnpj: "CNPJ: 30.481.525/0001-57",
        tableUrl: "/documents/4-Tabela-de-Pontuacao-Tokyo.pdf",
        planUrl: "/documents/4-Plano-Urbanistico-Tokyo.pdf",
        cards: [
          { label: "Pontuação", value: "80" },
          { label: "% Subvenção", value: "20%" },
          { label: "Valor da Subvenção", value: "R$ 1.374.267,65", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 5,
        title: "Edifício Bemca",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Rua Dom José de Barros, n° 177 - República, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: GAURAMA / LATER / EDUCARE",
        cnpj: "CNPJ: 49.333.941/0001-36, 49.334.725/0001-05, 49.334.634/0001-70",
        tableUrl: "/documents/5-Tabela-de-Pontuacao-IRR-Dom-Jose-de-Barros.pdf",
        planUrl: "/documents/5-Plano-Urbanistico-IRR-Dom-Jose-de-Barros.pdf",
        cards: [
          { label: "Pontuação", value: "76" },
          { label: "% Subvenção", value: "24%" },
          { label: "Valor da Subvenção", value: "R$ 1.899.702,48", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 6,
        title: "Edifício Anhumas",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Rua Marconi, nºs 101, 103 e 107 - República, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Condomínio Edifício Anhumas",
        cnpj: "CNPJ: 67.839.068/0001-30",
        tableUrl: "/documents/6-Tabela-de-Pontuacao-ILION.pdf",
        planUrl: "/documents/6-Plano-Urbanistico-ILION.pdf",
        cards: [
          { label: "Pontuação", value: "75" },
          { label: "% Subvenção", value: "18,75%" },
          { label: "Valor da Subvenção", value: "R$ 1.447.391,78", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 7,
        title: "Edifício Leon",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Rua Rego Freitas, nºs 57 e 73 - República, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Lidia Lerner Botsman e Silvia Lerner Attia",
        cnpj: "",
        tableUrl: "/documents/7-Tabela-de-Pontuacao-IRR-Rego-Freitas.pdf",
        planUrl: "/documents/7-Plano-Urbanistico-IRR-Rego-Freitas.pdf",
        cards: [
          { label: "Pontuação", value: "71" },
          { label: "% Subvenção", value: "22,75%" },
          { label: "Valor da Subvenção", value: "R$ 3.097.571,75", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 8,
        title: "Edifício Jandaia",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Rua Jandaia, nºs 112 e 122 - Bela Vista, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: D'Abril Empreendimentos Ltda.",
        cnpj: "CNPJ: 48.770.488/0001-62",
        tableUrl: "/documents/8-Tabela-de-Pontuacao-DAbril.pdf",
        planUrl: "/documents/8-Plano-Urbanistico-DAbril.pdf",
        cards: [
          { label: "Pontuação", value: "65" },
          { label: "% Subvenção", value: "21,25%" },
          { label: "Valor da Subvenção", value: "R$ 303.719,77", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 9,
        title: "Edifício Américo Destri",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Rua José Bonifácio, nºs 23 e 29 - Centro Histórico de São Paulo, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Trides Imóveis, Administração e Participações Ltda.",
        cnpj: "CNPJ: 13.648.906/0001-20",
        tableUrl: "/documents/9-Tabela-de-Pontuacao-Ilaria.pdf",
        planUrl: "/documents/9-Plano-Urbanistico-Ilaria.pdf",
        cards: [
          { label: "Pontuação", value: "65" },
          { label: "% Subvenção", value: "16,25%" },
          { label: "Valor da Subvenção", value: "R$ 793.771,20", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 10,
        title: "Edifício Líbero Badaró",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Rua Líbero Badaró, n° 370 - Centro Histórico de São Paulo, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Libero 370 Ltda.",
        cnpj: "CNPJ: 54.270.309/0001-20",
        tableUrl: "/documents/10-Tabela-de-Pontuacao-Libero370.pdf",
        planUrl: "/documents/10-Plano-Urbanistico-Libero370.pdf",
        cards: [
          { label: "Pontuação", value: "65" },
          { label: "% Subvenção", value: "16,25%" },
          { label: "Valor da Subvenção", value: "R$ 842.165,80", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 11,
        title: "Edifício Princesa Isabel",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Av. Rio Branco, nºs 749, 753 e 759 - Campos Elíseos, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Netuno22 Empreendimentos Imobiliários",
        cnpj: "CNPJ: 32.780.719/0001-89",
        tableUrl: "/documents/11-Tabela-de-Pontuacao-Neturno.pdf",
        planUrl: "/documents/11-Plano-Urbanistico-Neturno.pdf",
        cards: [
          { label: "Pontuação", value: "62,3805" },
          { label: "% Subvenção", value: "15,6%" },
          { label: "Valor da Subvenção", value: "R$ 2.171.191,27", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 12,
        title: "Edifício XV de Novembro",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Rua Quinze de Novembro, n° 194 - Centro Histórico de São Paulo, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: CAU-SP (Conselho de Arquitetura e Urbanismo)",
        cnpj: "CNPJ: 15.131.560/0001-52",
        tableUrl: "/documents/12-Tabela-de-Pontuacao-CAU.pdf",
        planUrl: "/documents/12-Plano-Urbanistico-CAU.pdf",
        cards: [
          { label: "Pontuação", value: "60" },
          { label: "% Subvenção", value: "15%" },
          { label: "Valor da Subvenção", value: "R$ 3.321.649,13", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 13,
        title: "Endutex Hotéis Brasil",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Av. Vieira de Carvalho, n° 99 - República, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Endutex Hotéis Brasil Ltda.",
        cnpj: "CNPJ: 12.415.686/0001-60",
        tableUrl: "/documents/13-Tabela-de-Pontuacao-ENDUTEX.pdf",
        planUrl: "/documents/13-Plano-Urbanistico-ENDUTEX.pdf",
        cards: [
          { label: "Pontuação", value: "60" },
          { label: "% Subvenção", value: "15%" },
          { label: "Valor da Subvenção", value: "R$ 1.343.672,18", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 14,
        title: "Edifício H Lara",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Praça Antônio Prado, nºs 17, 33 e 39 - Centro Histórico de São Paulo, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: LECREC Administração Imobiliária S.A.",
        cnpj: "CNPJ: 23.120.098/0001-16",
        tableUrl: "/documents/14-Tabela-de-Pontuacao-PLANTAINC.pdf",
        planUrl: "/documents/14-Plano-Urbanistico-PLANTAINC.pdf",
        cards: [
          { label: "Pontuação", value: "60" },
          { label: "% Subvenção", value: "15%" },
          { label: "Valor da Subvenção", value: "R$ 4.504.020,51", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 15,
        title: "Helvetia Empreendimento Imobiliário SPE",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Av. Casper Líbero, n° 452 - Centro Histórico de São Paulo, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Helvetia Empreendimento Imobiliário SPE Ltda.",
        cnpj: "CNPJ: 46.207.322/0001-07",
        tableUrl: "/documents/15-Tabela-de-Pontuacao-Helvetia.pdf",
        planUrl: "/documents/15-Plano-Urbanistico-Helvetia.pdf",
        cards: [
          { label: "Pontuação", value: "55" },
          { label: "% Subvenção", value: "13,75%" },
          { label: "Valor da Subvenção", value: "R$ 1.851.677,02", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 16,
        title: "Residencial Cambridge",
        edital: "Chamamento Público n° 01/2025/SMUL",
        address: "Rua Álvaro de Carvalho, n° 53 - Centro Histórico de São Paulo, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Condomínio Edifício Residencial Cambridge",
        cnpj: "CNPJ: 46.087.877/0001-62",
        tableUrl: "/documents/16-Tabela-de-Pontuacao-SOMAUMA.pdf",
        planUrl: "/documents/16-Plano-Urbanistico-SOMAUMA-1.pdf",
        cards: [
          { label: "Pontuação", value: "50" },
          { label: "% Subvenção", value: "12,5%" },
          { label: "Valor da Subvenção", value: "R$ 43.318,84", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
    ],
  },
];

export const chamamentos2024 = [
  {
    id: "group-1",
    headerTitle: "Chamamento Público nº 02/2024/SMUL",
    items: [
      {
        id: 1,
        title: "Edifício Santa Therezinha",
        edital: "Chamamento Público nº 02/2024/SMUL",
        address: "Rua José Bonifácio, nºs 237, 241 e 245 - Sé, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Projetech: Projetos Técnicos e Sociais",
        cnpj: "CNPJ: 08.218.640/0001-84",
        tableUrl: "/documents/1-Tabela-de-Pontuacao-Projetech.pdf",
        planUrl: "/documents/1-Plano-Urbanistico-Projetech.pdf",
        cards: [
          { label: "Pontuação", value: "85" },
          { label: "% Subvenção", value: "21,25%" },
          { label: "Valor da Subvenção", value: "R$ 3.363.074,44", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 2,
        title: "Antigo Hotel Columbia Palace",
        edital: "Chamamento Público nº 02/2024/SMUL",
        address: "Av. São João, nºs 578 e 588 - República, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Associação Portal da Juta - 1º de Maio",
        cnpj: "CNPJ: 02.577.573/0001-08",
        tableUrl: "/documents/2-Tabela-de-Pontuacao-Associacao-Portal-da-Juta.pdf",
        planUrl: "/documents/2-Plano-Urbanistico-Associacao-Portal-da-Juta.pdf",
        cards: [
          { label: "Pontuação", value: "80" },
          { label: "% Subvenção", value: "20,00%" },
          { label: "Valor da Subvenção", value: "R$ 2.946.971,44", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 3,
        title: "Edifício Cialga",
        edital: "Chamamento Público nº 02/2024/SMUL",
        address: "Rua Santa Isabel, n° 181 / Rua Amaral Gurgel, n° 161 - Vila Buarque, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: SANTABEL EMPREENDIMENTOS LTDA.",
        cnpj: "CNPJ: 58.799.834/0001-99",
        tableUrl: "/documents/3-Tabela-de-Pontuacao-SANTABEL.pdf",
        planUrl: "/documents/3-Plano-Urbanistico-SANTABEL.pdf",
        cards: [
          { label: "Pontuação", value: "65" },
          { label: "% Subvenção", value: "16,25%" },
          { label: "Valor da Subvenção", value: "R$ 2.459.719,84", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00 (Desistência)", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 4,
        title: "Edifício Tácito de Toledo Lara",
        edital: "Chamamento Público nº 02/2024/SMUL",
        address: "Largo da Misericórdia, n° 20 - Centro Histórico de São Paulo, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: SM02 - EDIFICIO TTL SPE LTDA.",
        cnpj: "CNPJ: 44.380.369/0001-42",
        tableUrl: "/documents/4-Tabela-de-Pontuacao-SM02.pdf",
        planUrl: "/documents/4-Plano-Urbanistico-SM02.pdf",
        cards: [
          { label: "Pontuação", value: "60" },
          { label: "% Subvenção", value: "15,00%" },
          { label: "Valor da Subvenção", value: "R$ 1.547.750,10", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 308.449,74", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 5,
        title: "Edifício Marquês de Itu",
        edital: "Chamamento Público nº 02/2024/SMUL",
        address: "Rua Marquês de Itu, nºs 80, 84, 88, 90 e 92 - Vila Buarque, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: MI88 EMPREENDIMENTOS E PARTICIPACOES LTDA.",
        cnpj: "CNPJ: 54.459.034/0001-78",
        tableUrl: "/documents/5-Tabela-de-Pontuacao-MI88.pdf",
        planUrl: "/documents/5-Plano-Urbanistico-MI88.pdf",
        cards: [
          { label: "Pontuação", value: "55" },
          { label: "% Subvenção", value: "13,75%" },
          { label: "Valor da Subvenção", value: "R$ 916.945,58", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 823.324,90", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 6,
        title: "Edifício Astoria",
        edital: "Chamamento Público nº 02/2024/SMUL",
        address: "Rua Sete de Abril, nºs 253, 257 e 261 - República, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: ORGANIZACAO TOLEDO LARA LTDA.",
        cnpj: "CNPJ: 01.808.926/0001-70",
        tableUrl: "/documents/6-Tabela-de-Pontuacao-Toledo-Lara.pdf",
        planUrl: "/documents/6-Plano-Urbanistico-Toledo-Lara.pdf",
        cards: [
          { label: "Pontuação", value: "55" },
          { label: "% Subvenção", value: "13,75%" },
          { label: "Valor da Subvenção", value: "R$ 1.988.289,11", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 396.557,58", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 7,
        title: "Edifício Independência",
        edital: "Chamamento Público nº 02/2024/SMUL",
        address: "Rua General Jardim, nºs 32, 36 e 44 - Vila Buarque, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: CENTRAL CAPITAL SPE II LTDA.",
        cnpj: "CNPJ: 50.564.562/0001-36",
        tableUrl: "/documents/7-Tabela-de-Pontuacao-Central-Capital.pdf",
        planUrl: "/documents/7-Plano-Urbanistico-Central-Capital.pdf",
        cards: [
          { label: "Pontuação", value: "55" },
          { label: "% Subvenção", value: "13,75%" },
          { label: "Valor da Subvenção", value: "R$ 2.791.026,18", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 2.507.522,43", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 8,
        title: "Edifício Vera",
        edital: "Chamamento Público nº 02/2024/SMUL",
        address: "Rua Álvares Penteado, nºs 75, 83 e 87 - Centro Histórico de São Paulo, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Elza Lara Loeb",
        cnpj: "",
        tableUrl: "/documents/8-Tabela-de-Pontuacao-Elza-Lara-Loeb.pdf",
        planUrl: "/documents/8-Plano-Urbanistico-Elza-Lara-Loeb.pdf",
        cards: [
          { label: "Pontuação", value: "55" },
          { label: "% Subvenção", value: "13,75%" },
          { label: "Valor da Subvenção", value: "R$ 1.206.037,94", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 9,
        title: "Edifício Santa Maria",
        edital: "Chamamento Público nº 02/2024/SMUL",
        address: "Rua do Tesouro, nºs 47, 49 e 53 - Centro Histórico de São Paulo, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Celso Figueiredo Neto",
        cnpj: "",
        tableUrl: "/documents/9-Tabela-de-Pontuacao-Celso-Figueiredo-Neto.pdf",
        planUrl: "/documents/9-Plano-Urbanistico-Celso-Figueiredo-Neto.pdf",
        cards: [
          { label: "Pontuação", value: "55" },
          { label: "% Subvenção", value: "13,75%" },
          { label: "Valor da Subvenção", value: "R$ 904.790,84", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 10,
        title: "LAF Sete de Abril",
        edital: "Chamamento Público nº 02/2024/SMUL",
        address: "Rua Sete de Abril, nºs 338, 342 e 346 - República, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: LAF SETE DE ABRIL SPE LTDA.",
        cnpj: "CNPJ: 55.419.677/0001-50",
        tableUrl: "/documents/10-Tabela-de-Pontuacao-LAF.pdf",
        planUrl: "/documents/10-Plano-Urbanistico-LAF.pdf",
        cards: [
          { label: "Pontuação", value: "55" },
          { label: "% Subvenção", value: "13,75%" },
          { label: "Valor da Subvenção", value: "R$ 1.702.057,18", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 339.311,16", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 11,
        title: "Edifício Comendador Artin Kalaigian",
        edital: "Chamamento Público nº 02/2024/SMUL",
        address: "Largo do Arouche, n° 337 - Santa Cecília, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: CONDOMÍNIO EDIFÍCIO COMENDADOR ARTIN KALAIGIAN",
        cnpj: "CNPJ: 69.293.470/0001-97",
        tableUrl: "/documents/11-Tabela-de-Pontuacao-Artin-Kalaigian.pdf",
        planUrl: "/documents/11-Plano-Urbanistico-Artin-Kalaigian.pdf",
        cards: [
          { label: "Pontuação", value: "55" },
          { label: "% Subvenção", value: "13,75%" },
          { label: "Valor da Subvenção", value: "R$ 1.001.639,99", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 996.138,59", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 12,
        title: "Edifício B. Luiz Antonio",
        edital: "Chamamento Público nº 02/2024/SMUL",
        address: "Av. Brigadeiro Luís Antônio, nºs 483 e 487 - Bela Vista, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: LRBO ADMINISTRACAO DE IMOVEIS LTDA.",
        cnpj: "CNPJ: 13.876.878/0001-37",
        tableUrl: "/documents/12-Tabela-de-Pontuacao-LRBO.pdf",
        planUrl: "/documents/12-Plano-Urbanistico-LRBO.pdf",
        cards: [
          { label: "Pontuação", value: "50" },
          { label: "% Subvenção", value: "12,50%" },
          { label: "Valor da Subvenção", value: "R$ 2.093.636,38", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 0,00", valueClassName: "text-green-700" },
        ],
      },
    ],
  },
];

export const chamamentos2023 = [
  {
    id: "group-1",
    headerTitle: "Chamamento Público nº 01/2023/SMUL",
    items: [
      {
        id: 1,
        title: "Edifício Taquari",
        edital: "Chamamento Público nº 01/2023/SMUL",
        address: "Av. Ipiranga, nºs 952 e 958 - República, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Taquari Agro Comercial LTDA",
        cnpj: "CNPJ: 62.218.425/0001-29",
        tableUrl: "/documents/Tabela-de-Pontuacao-Ed.-Taquari.pdf",
        planUrl: "/documents/Taquari-Agro-Comercial-LTDA-Plano-Urbanistico.pdf",
        cards: [
          { label: "Pontuação", value: "49,85" },
          { label: "% Subvenção", value: "12,46%" },
          { label: "Valor da Subvenção", value: "R$ 1.065.703,30", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 952.680,01", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 2,
        title: "Edifício Dona Marcha",
        edital: "Chamamento Público nº 01/2023/SMUL",
        address: "Av. Duque de Caxias, nºs 408 e 141 - Santa Ifigênia, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: Duque de Caxias 408 LTDA",
        cnpj: "CNPJ: 51.203.312/0001-33",
        tableUrl: "/documents/Tabela-de-Pontuacao-Ed.-Dona-Marcha.pdf",
        planUrl: "/documents/Duque-de-Caxias-408-LTDA-Plano-Urbanistico.pdf",
        cards: [
          { label: "Pontuação", value: "44,34" },
          { label: "% Subvenção", value: "11,09%" },
          { label: "Valor da Subvenção", value: "R$ 869.833,29", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 861.767,09", valueClassName: "text-green-700" },
        ],
      },
      {
        id: 3,
        title: "Edifício Virgínia",
        edital: "Chamamento Público nº 01/2023/SMUL",
        address: "Rua Martins Fontes, nºs 197, 205, 213 e 223 - República, São Paulo/SP.",
        responsible: "Responsável pelo imóvel: SM01 - Edifício Virgínia SPE S/A",
        cnpj: "CNPJ: 47.171.025/0001-11",
        tableUrl: "/documents/Tabela-de-Pontuacao-Ed.-Virginia.pdf",
        planUrl: "/documents/SM01-Edificio-Virginia-SPE-SA-Plano-Urbanistico.pdf",
        cards: [
          { label: "Pontuação", value: "44,23" },
          { label: "% Subvenção", value: "11,06%" },
          { label: "Valor da Subvenção", value: "R$ 2.647.136,35", valueClassName: "text-(--button-background)" },
          { label: "Valor pago", value: "R$ 2.639.070,16", valueClassName: "text-green-700" },
        ],
      },
    ],
  },
];
